elit_application:
    resource: "@ElitBundle/Resources/config/routing/application.yml"
    prefix:   /application


elit_classes:
    resource: "@ElitBundle/Resources/config/routing/classes.yml"
    prefix:   /classes

elit_homepage:
    path:     /
    defaults: { _controller: ElitBundle:Default:index }

ajout_student:
    path:     /S
    defaults: { _controller: ElitBundle:Student:ajout }


affiche_student:
    path:     /A
    defaults: { _controller: ElitBundle:Student:affiche }