module_index:
    path:     /
    defaults: { _controller: "ElitBundle:Module:index" }
    methods:  GET

module_show:
    path:     /{id}/show
    defaults: { _controller: "ElitBundle:Module:show" }
    methods:  GET

module_new:
    path:     /new
    defaults: { _controller: "ElitBundle:Module:new" }
    methods:  [GET, POST]

module_edit:
    path:     /{id}/edit
    defaults: { _controller: "ElitBundle:Module:edit" }
    methods:  [GET, POST]

module_delete:
    path:     /{id}/delete
    defaults: { _controller: "ElitBundle:Module:delete" }
    methods:  DELETE
